version: 3

tasks:
  run:
    desc: Starts project
    cmds:
      - cd backend && go run ./cmd/main.go

  generate:
    desc: Generates code based on GQL schema and Protobuf files
    cmds:
      - gqlgen generate --config backend/config/gqlgen.yml